version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8010:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: bbdd
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: bbdd
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
    - 8015:80

volumes:
  wordpress:
  db:
  phpmyadmin: